apiVersion: v1
kind: Service
metadata:
  name: log-processor-service
spec:
  selector:
    app: log-processor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

