apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
    spec:
      containers:
      - name: log-processor
        image: sharvarig14/log-processor:latest
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: LOG_TOPIC
          value: "logs"
        - name: PROCESSED_TOPIC
          value: "processed-logs"

