# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy application files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir flask kafka-python google-cloud-storage gunicorn

# Expose Flask port (if needed)
EXPOSE 5000

# Command to run your application
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]

