apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: sharvarig14/log-generator:latest
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-controller.default.svc.cluster.local:9092"
        - name: LOG_TOPIC
          value: "logs"
        - name: SECURITY_PROTOCOL
          value: "PLAINTEXT"


